import { useState } from 'react'
import type { ChoiceNode, EndNode, GdNoteNode, MarginsNode, Node, OpponentList, Zone } from '../scenarioTree'

// ── Interactive "drill-down" scenario for a single team ──────────────────────
// The tree is generated by `buildGroupScenarios` (src/scenarioTree.ts) from the
// deterministic engine; this component only walks and renders it.
// Self-contained: injects its own `.scn`-scoped CSS once on import.

// Best-third heuristic: 8 of 12 thirds advance (two-thirds), ranked points → GD →
// goals. Calibrated against the equivalent UEFA Euro 4-of-6 format. Approximate.
function viabilityOf(points: number, gd?: number) {
  if (points >= 4) return { level: 'in', label: 'Almost certain', segs: 5 }
  if (points === 3) return gd != null && gd >= 0 ? { level: 'likely', label: 'Likely', segs: 4 } : { level: 'borderline', label: 'Borderline', segs: 3 }
  if (points === 2) return { level: 'borderline', label: 'Long shot', segs: 2 }
  return { level: 'out', label: 'Out', segs: 1 }
}

// ── views ────────────────────────────────────────────────────────────────────
const zoneCls = (z: Zone) => (z === 'good' ? 'good' : z === 'bad' ? 'bad' : 'mid')
const fmtGD = (n: number) => (n >= 0 ? `+${n}` : `${n}`)

function Opponents({ list }: { list: OpponentList }) {
  const label = list.kind === 'runnerUp' ? 'R32 opponents · group runner-up' : 'Possible R32 opponents · a best third'
  return (
    <div className="opps">
      <span className="lab">{label}</span>
      {list.groups.map(({ g, teams }) => (
        <div className="row" key={g}>
          <span className="g">{g}</span>
          {teams.map((t, i) => (
            <span key={t}>{i > 0 && <span className="sep">·</span>}<b>{t}</b></span>
          ))}
        </div>
      ))}
    </div>
  )
}

function Viability({ points, gd }: { points: number; gd?: number }) {
  const v = viabilityOf(points, gd)
  return (
    <>
      <div className={`v3 v-${v.level}`}>
        <span className="v-lbl">Best-third odds</span>
        <span className="track">{[0, 1, 2, 3, 4].map((i) => <span key={i} className={`seg ${i < v.segs ? 'on' : ''}`} />)}</span>
        <span className="v-tag">{v.label}</span>
        <span className="v-basis">· {points} pts{gd != null ? `, GD ${fmtGD(gd)}` : ''}</span>
      </div>
      <div className="third-rule">8 of 12 thirds advance, ranked on points then goal difference. 4 pts is safe; 3 usually enough; 2 or fewer rarely.</div>
    </>
  )
}

type Item =
  | { t: 'choice'; node: ChoiceNode; depth: number; sel: number | null; single: boolean }
  | { t: 'margins'; node: MarginsNode; both: boolean; selfGD: number; rivalGD: number }
  | { t: 'gdnote'; node: GdNoteNode }
  | { t: 'result'; node: EndNode; label?: string; liveGD?: number }

function Flow({ root }: { root: Node }) {
  const [picks, setPicks] = useState<number[]>([])
  const [sm, setSm] = useState<number | null>(null)
  const [rm, setRm] = useState<number | null>(null)

  const pick = (depth: number, idx: number) => {
    setPicks((prev) => (prev[depth] === idx ? prev.slice(0, depth) : [...prev.slice(0, depth), idx]))
    setSm(null)
    setRm(null)
  }

  const items: Item[] = []
  let node: Node | null = root
  let depth = 0
  let carryLabel: string | null = null
  while (node) {
    if (node.type === 'choice') {
      const single: boolean = node.options.length === 1
      const sel: number | null = single ? 0 : depth < picks.length ? picks[depth] : null
      items.push({ t: 'choice', node, depth, sel, single })
      carryLabel = single ? node.options[0].label : null
      if (sel === null) break
      node = node.options[sel].child
      depth++
    } else if (node.type === 'margins') {
      carryLabel = null
      const both = sm !== null && rm !== null
      const selfGD = node.self.gd + (sm ?? 0)
      const rivalGD = node.rival.gd + (rm ?? 0)
      items.push({ t: 'margins', node, both, selfGD, rivalGD })
      if (!both) {
        items.push({ t: 'result', node: { type: 'end', place: `${node.win.place} / ${node.lose.place}`, zone: 'mid', set: node.set, text: 'Set both winning margins to see where it lands.' } })
      } else {
        const resolved = selfGD > rivalGD ? node.win : node.lose
        items.push({ t: 'result', node: resolved, liveGD: selfGD })
      }
      node = null
    } else if (node.type === 'gdnote') {
      carryLabel = null
      items.push({ t: 'gdnote', node })
      items.push({ t: 'result', node: node.result })
      node = null
    } else {
      items.push({ t: 'result', node, label: carryLabel ?? undefined })
      carryLabel = null
      node = null
    }
  }

  const stepperEl = (val: number | null, set: (n: number | null) => void, label: string) => (
    <div className="mrow">
      <span className="mteam">{label}</span>
      <span className="stepper">
        <button type="button" onClick={() => set(val === null ? null : val <= 1 ? null : val - 1)} aria-label="less">−</button>
        <span className={`val ${val === null ? 'unset' : ''}`}>{val === null ? '?' : val}</span>
        <button type="button" onClick={() => set(val === null ? 1 : Math.min(9, val + 1))} aria-label="more">+</button>
      </span>
    </div>
  )

  return (
    <div className="flow">
      {items.map((it, i) => {
        if (it.t === 'choice') {
          const colour = it.node.kind === 'parallel' ? 'blue' : ''
          return (
            <div className={`step ${colour}`} key={i}>
              <div className="s-head">
                {it.node.kind === 'own' ? (
                  <>
                    <div className="s-eyebrow">Last match</div>
                    <div className="s-title"><span className="vs">vs</span> {it.node.vs}</div>
                  </>
                ) : (
                  <>
                    <div className="s-eyebrow">Watch · {it.node.match}</div>
                    {it.node.rootFor && <div className="s-root"><span className="rk">Root for</span><b>{it.node.rootFor}</b></div>}
                  </>
                )}
              </div>
              {!it.single && (
                <div className="opts">
                  {it.node.options.map((o, oi) => {
                    const selected = it.sel === oi
                    const dimmed = it.sel !== null && !selected
                    return (
                      <button
                        type="button"
                        className={`opt ${selected ? 'sel' : ''} ${dimmed ? 'dim' : ''}`}
                        key={o.label}
                        onClick={() => pick(it.depth, oi)}
                      >
                        <span className="ol">{o.label}</span>
                        {!selected && <span className={`op ${zoneCls(o.zone)}`}>{o.place}</span>}
                      </button>
                    )
                  })}
                </div>
              )}
            </div>
          )
        }
        if (it.t === 'margins') {
          return (
            <div className="step amber" key={i}>
              <div className="s-head"><div className="s-eyebrow">Then set · the winning margins</div></div>
              <div className="s-note">{it.node.note}</div>
              <div className="margins">
                {stepperEl(sm, setSm, `${it.node.self.team} win by`)}
                {stepperEl(rm, setRm, `${it.node.rival.team} win by`)}
              </div>
              {it.both && <div className="gd-live">{it.node.self.team} GD <b>{fmtGD(it.selfGD)}</b> · {it.node.rival.team} GD <b>{fmtGD(it.rivalGD)}</b></div>}
            </div>
          )
        }
        if (it.t === 'gdnote') {
          return (
            <div className="step amber" key={i}>
              <div className="s-head"><div className="s-eyebrow">Decided on goal difference</div></div>
              <div className="gd-live">{it.node.self.team} GD <b>{fmtGD(it.node.self.gd)}</b> · {it.node.rival.team} GD <b>{fmtGD(it.node.rival.gd)}</b></div>
            </div>
          )
        }
        const r = it.node
        return (
          <div className="step result" key={i}>
            <div className="r-head">
              <span className="r-lbl">{it.label ?? 'Result'}</span>
              <span className={`r-place ${zoneCls(r.zone)}`}>{r.place}</span>
            </div>
            {r.text && <div className="r-note">{r.text}</div>}
            {r.third && <Viability points={r.third.points} gd={it.liveGD ?? r.third.gd} />}
            {r.opponents && <Opponents list={r.opponents} />}
          </div>
        )
      })}
    </div>
  )
}

/** Renders the interactive drill-down for a team's pre-built scenario tree. */
export function ScenarioFlow({ root }: { root: Node }) {
  if (!root) return null
  return (
    <div className="scn">
      <Flow root={root} />
    </div>
  )
}

// ── scoped CSS, injected once ────────────────────────────────────────────────
const SCENARIO_CSS = `
  .scn{ --win:#34c08a; --draw:#e0a44a; --lose:#e06f6e; --info:#5aa0e6; --txt:#eef1f5; --txt2:#9aa4b2; --txt3:#6b7585; --panel2:#181e26; --line:rgba(255,255,255,.07); color:var(--txt); }
  .scn .flow{padding:16px 16px 18px 14px;}
  .scn .step{position:relative; padding:0 0 22px 28px; border-left:1px solid var(--line); margin-left:6px;}
  .scn .step:last-child{border-left-color:transparent; padding-bottom:0;}
  .scn .step::before{content:""; position:absolute; left:-5px; top:3px; width:9px; height:9px; border-radius:50%; background:var(--txt3);}
  .scn .step.blue::before{background:var(--info);}
  .scn .step.amber::before{background:var(--draw);}
  .scn .step.result::before{background:var(--win); width:11px; height:11px; left:-6px;}
  .scn .step.blue{box-shadow:inset 1px 0 0 var(--info);}
  .scn .step.amber{box-shadow:inset 1px 0 0 var(--draw);}
  .scn .s-head{margin-bottom:11px;}
  .scn .s-eyebrow{font-size:10px; font-weight:700; letter-spacing:.6px; text-transform:uppercase; color:var(--txt3);}
  .scn .step.blue .s-eyebrow{color:var(--info);}
  .scn .step.amber .s-eyebrow{color:#e8b35e;}
  .scn .s-title{font-size:14px; font-weight:700; color:var(--txt); margin-top:2px;}
  .scn .s-title .vs{color:var(--txt2); font-weight:600;}
  .scn .s-root{font-size:11.5px; color:var(--txt2); margin-top:3px;}
  .scn .s-root .rk{font-size:9.5px; font-weight:700; letter-spacing:.5px; text-transform:uppercase; color:var(--txt3); margin-right:5px;}
  .scn .s-root b{color:var(--info); font-weight:700;}
  .scn .opts{display:flex; flex-direction:column; gap:6px;}
  .scn .opt{display:flex; align-items:center; gap:12px; width:100%; text-align:left; padding:10px 13px; border-radius:9px; background:var(--panel2); border:1px solid var(--line); color:var(--txt); font:inherit; cursor:pointer; transition:background .12s, border-color .12s, opacity .12s;}
  .scn .opt:hover{border-color:rgba(255,255,255,.3); background:#1c232d;}
  .scn .opt.sel{border-color:rgba(255,255,255,.34); background:#1c232d; cursor:default;}
  .scn .opt.dim{opacity:.42; background:transparent;} .scn .opt.dim:hover{opacity:.8; border-color:rgba(255,255,255,.2);}
  .scn .opt .ol{font-size:13px; font-weight:700; letter-spacing:.3px;}
  .scn .op{margin-left:auto; font-size:15px; font-weight:700;}
  .scn .op.good{color:#5fd6ad;} .scn .op.mid{color:#e8b35e;} .scn .op.bad{color:#e88;}
  .scn .s-note{font-size:11.5px; color:var(--txt2); margin:0 0 11px;}
  .scn .margins{display:flex; flex-direction:column; gap:9px;}
  .scn .mrow{display:flex; align-items:center; gap:10px;}
  .scn .mteam{font-size:13px; color:var(--txt);}
  .scn .stepper{margin-left:auto; display:inline-flex; align-items:center; gap:8px;}
  .scn .stepper button{width:26px; height:26px; border-radius:6px; border:1px solid var(--line); background:var(--panel2); color:var(--txt); cursor:pointer; font-size:15px; line-height:1;}
  .scn .stepper button:hover{border-color:rgba(255,255,255,.25);}
  .scn .stepper .val{min-width:18px; text-align:center; font-weight:700; font-variant-numeric:tabular-nums;}
  .scn .stepper .val.unset{color:var(--txt3);}
  .scn .gd-live{font-size:11.5px; color:var(--txt3); margin-top:11px; font-variant-numeric:tabular-nums;}
  .scn .gd-live b{color:var(--txt2);}
  .scn .r-head{display:flex; align-items:baseline; gap:12px;}
  .scn .r-lbl{font-size:10px; font-weight:700; letter-spacing:.6px; text-transform:uppercase; color:var(--txt3);}
  .scn .r-place{margin-left:auto; font-size:22px; font-weight:700; line-height:1;}
  .scn .r-place.good{color:#5fd6ad;} .scn .r-place.mid{color:#e8b35e;} .scn .r-place.bad{color:#e88;}
  .scn .r-note{font-size:11.5px; color:var(--txt2); margin-top:9px;}
  .scn .opps{margin-top:11px; font-size:12px; color:var(--txt2); line-height:1.55;}
  .scn .opps .lab{display:block; font-size:10px; font-weight:700; letter-spacing:.5px; color:var(--txt3); text-transform:uppercase; margin-bottom:4px;}
  .scn .opps .row{margin-bottom:2px;} .scn .opps .g{display:inline-block; min-width:16px; color:var(--txt3); font-weight:700; font-size:11px; margin-right:6px;}
  .scn .opps b{color:var(--txt); font-weight:600;} .scn .opps .sep{color:var(--txt3); padding:0 2px;}
  .scn .v3{display:flex; align-items:center; gap:7px; margin-top:11px; flex-wrap:wrap;}
  .scn .v3 .v-lbl{font-size:9.5px; font-weight:700; letter-spacing:.4px; text-transform:uppercase; color:var(--txt3);}
  .scn .v3 .track{display:inline-flex; gap:3px;}
  .scn .v3 .seg{width:13px; height:4px; border-radius:2px; background:rgba(255,255,255,.09);}
  .scn .v3 .v-tag{font-size:11px; font-weight:700;}
  .scn .v3 .v-basis{font-size:10.5px; color:var(--txt3); font-variant-numeric:tabular-nums;}
  .scn .v-in .seg.on{background:var(--win);} .scn .v-in .v-tag{color:#5fd6ad;}
  .scn .v-likely .seg.on{background:var(--win);} .scn .v-likely .v-tag{color:#5fd6ad;}
  .scn .v-borderline .seg.on{background:var(--draw);} .scn .v-borderline .v-tag{color:#e8b35e;}
  .scn .v-out .seg.on{background:var(--lose);} .scn .v-out .v-tag{color:#e88;}
  .scn .third-rule{margin-top:7px; font-size:10.5px; color:var(--txt3); line-height:1.45;}
`

if (typeof document !== 'undefined' && !document.querySelector('style[data-scn]')) {
  const el = document.createElement('style')
  el.setAttribute('data-scn', 'flow')
  el.textContent = SCENARIO_CSS
  document.head.appendChild(el)
}
